import json,pathlib
p=pathlib.Path('research_notes/Goal step dependency audit')
cat=json.loads((p/'catalogue.json').read_text(encoding='utf-8'))['Forever']
D='https://github.com/Questie/Questie/blob/v10.0.0/Database/Classic/classicQuestDB.lua'
F='https://github.com/Questie/Questie/blob/v10.0.0/Database/Corrections/classicQuestFixes.lua'
def q(n): return f'https://www.wowhead.com/classic/quest={n}'
def item(n): return f'https://www.wowhead.com/classic/item={n}'
def row(deps='',kind='independent / no lock',confidence='High Classic; unconfirmed Forever',note='',sources=None): return dict(prerequisites=deps,classification=kind,confidence=confidence,reason=note,sources=sources or [D])
def hard(deps,note='',sources=None,confidence='High Classic; unconfirmed Forever'):return row(deps,'hard prerequisite',confidence,note,sources)
def soft(deps,note='',sources=None):return row(deps,'soft/contextual; no lock','Medium Classic; unconfirmed Forever',note,sources)
M={}
M['ashbringer']=[row(note='No earlier step.'),hard('1','Naxx attunement minimum level 60; att_naxx completion can satisfy this without tracking that goal.',[q(9121),D]),soft('2','Naxx entry requires attunement on raiding character; already attuned alt / cleared instance evidence must override.',[q(9121)]),soft('3','Gothik is instance route progression, not a permanently required personal kill. Joining a raid already at Four Horsemen is allowed.',[item(22691)]),hard('4','Chest becomes available after encounter; item evidence overrides missing personal boss history.',[item(22691)])]
M['frostsaber']=[row(confidence='Data conflict: Classic quest level58 versus current level40',note='Classic Questie records quests4970/5201/5981 min58, so step1 cannot prove actual eligibility.',sources=[q(4970),D]),soft('1','Current step1 level40 insufficient Classic quest gate. Do not encode until Forever level rules checked.'),soft('2','Step2 first reputation point is implied by later cumulative milestone; avoid hiding farm.'),hard('3','Winterfall Intrusion unlocks at1500 neutral; alternative quests still earn Friendly.',[q(5201),D]),soft('4','Honored is cumulative reputation; Rampaging Giants unlocked there, but other repeatables still work.',[q(5981),D]),soft('5','Exalted cumulative reputation; do not force use of particular repeatables.',[q(5981),D]),row(note='Independent Darnassus reputation grind; NightElf skips. Required to USE under old race riding rules, not necessarily BUY.',sources=[item(13086)]),hard('6','Purchase Wintersaber Exalted gate; Darnassus step7 relates riding, do not add as buy prerequisite without Forever verification.',[item(13086)])]
M['atiesh']=[row(note='Preparation, auto level60 does not prove class/raids. No lock.'),row(note='Collect splinters independently; Naxx attunement on same caster is external entry gate.',sources=[item(22726)]),hard('2','40 splinters consumed to form frame.',[item(22727)]),hard('3','Frame starts9250. Also Anachronos requires nonhostile/Neutral Brood reputation; unrepresented external condition.',[q(9250)]),hard('4','Accept9251 after9250 before quest-item boss loot; no order versus step6.',[q(9251),D],confidence='Medium drop gating; high chain; unconfirmed Forever'),hard('4','Accept9251 after9250 before quest-item boss loot; parallel with step5.',[q(9251),D],confidence='Medium drop gating; high chain; unconfirmed Forever'),hard('5 AND 6','Both pieces required for9251.',[q(9251),D]),row(kind='data wording invalid; withhold lock',confidence='High inconsistency',note='Step says COMPLETE purification before defeating entity in step9, but9257/9269/9270/9271 completion includes entity defeat and final return. Should say PICK UP purification; then7→8→9→10.',sources=[q(9257),D]),row(kind='blocked by data correction',confidence='High chain; ambiguous current step8',note='Requires purification quest ACTIVE after7, not completed current8. Encode only after rewording8.',sources=[q(9257)]),hard('9','Receive reward when turning in class purification; step8 current COMPLETE redundantly includes9/10.',[q(9257),D])]
M['rhokdelar']=[row(note='External Lokdelar step7 yields stave; reward item/quest7636 evidence can satisfy without cross-goal active ticks.',sources=[q(7636)]),row(note='Requires The Ancient Leaf7632 = lokdelar step2, NOT stave completion in current step1. This can run alongside four demons.',sources=[q(7635),D]),row(note='Black sinew can be obtained before quest; own Onyxia attunement required to enter but avoid cross-goal lock.',sources=[item(18705),q(7635)]),hard('2 AND 3','Turn-in to STOMA, not Vartrus (current text wrong).', [q(7635),D]),hard('1 AND 4','Stave and enchanted string both consumed.',[item(18713)])]
M['lokdelar']=[row(note='Independent raid drop; personal MC attunement optional shortcut.',sources=[item(18703)]),hard('1','Leaf starts7632, which unlocks7636.',[q(7632),q(7636),D])]+[hard('2','7636 active; all four demons available in parallel, not sequential.',[q(7636),D]) for _ in range(4)]+[hard('3 AND 4 AND 5 AND 6','Four demon heads all required.',[q(7636),D])]
M['thunderfury']=[row(note='Weekly raiding is preparation, level60 auto not actual history.'),row(note='Independent binding loot; no ordering versus right binding.',sources=[item(18563)]),row(note='Independent binding loot; no ordering versus left binding.',sources=[item(18564)]),hard('2 OR 3','Either binding obtains Vessel19016 and starts7785. Do not require both.',[q(7785),D]),row(note='Buy bars or gather/smelt; do not hard-lock on raw materials6/7/8.',sources=[item(17771)]),row(note='Parallel raw ingredient of step5, consumed in Elementium; NOT an extra final turn-in.',sources=[q(7786),item(17771)]),row(note='Parallel raw ingredient of step5; NOT extra final turn-in.',sources=[q(7786),item(17771)]),row(note='Parallel raw ingredient of step5; NOT extra final turn-in.',sources=[q(7786),item(17771)]),hard('4','Must ACCEPT7786 after7785 before Essence drops. Step4 says start but auto only completed7785; improve watch evidence.',[q(7785),q(7786)]),hard('2 AND 3 AND 4 AND 5 AND 9','Final summon turn-in requires both bindings,10 bars,Essence. Do not also require consumed raw ingredients6/7/8.',[q(7786),D]),hard('10','Summons Prince; CURRENT auto quest7786 incorrectly ticks defeat at summon turn-in, before kill.',[q(7786),q(7787)]),hard('11','Loot Dormant Wind Kissed Blade19018 to start7787. Completion proof overrides missed kill.',[q(7787),D])]
M['benediction']=[row(note='Independent Eye raid drop.',sources=[item(18646)]),hard('1','Eye equipped to see/interact with Eris and take7622.',[q(7622),item(18646)]),hard('2','Event for7622 rewards Splinter.',[q(7622)]),row(note='Tradeable Eye of Shadow may be bought/farmed at any time.',sources=[item(18665)]),hard('1 AND 3 AND 4','All three components required/consumed.',[item(18608)])]
M['sulfuras']=[row(note='Preparation; not valid hard gate to purchasing materials.'),row(note='Eye independent of all preparation/materials.',sources=[item(17204)]),row(note='One Ingot required externally, not ALL eight of step4; plans can be bought; crafter may already know recipe.',sources=[q(7604),item(18592)])]+[row(note='Materials can be collected/bought in any order; Black Forge needed only if personally smelting Dark Iron.',sources=[item(18592)]) for _ in range(7)]+[row(note='Can use another blacksmith; own skill rule cannot prove service found.',sources=[item(18592)]),row(kind='conditional crafting AND; no universal hard lock',note='If personally commissioning craft needs4..10 and recipe on crafter/BS300. Hammer is BoE and may be bought, bypassing3..11. No universal checkbox gate.',sources=[item(17193),item(18592)]),hard('2 AND 12','Eye plus completed hammer required.',[item(17182)])]
M['mount_dreadsteed']=[row(note='Warlock level60 start.'),hard('1','7563 follows7562.',[q(7563),D]),hard('2','7564 follows7563.',[q(7564),D]),row(kind='UNRELATED; remove/remap in guide fix',note='7603 is Inferno spell chain7601→7602→7603 atlevel50, not Dreadsteed. No dependency from3 and no dependency into5.',sources=[q(7603),D]),hard('3 + external7625','Imp Delivery7629 requires7564 AND Xorothian Stardust7625. Missing chain7623→7624→7625.',[q(7629),D]),hard('3 + external7626 AND7627 AND7628','Arcanite7630 requires Bell/Wheel/Candle material turn-ins, available after7564; may parallel Imp Delivery, NOT gated by5.',[q(7630),D]),hard('5 AND 6','Dreadsteed quest7631 requires7629 AND7630; another warlock may supply reusable ritual tools; unrelated4 never gate.',[q(7631),D,F])]
M['mount_charger']=[row(note='Paladin level60 starter.'),hard('1',sources=[q(7637),D]),hard('2',sources=[q(7639),D]),hard('3',sources=[q(7640),D]),row('4','uncertain ordering; withhold lock','Conflicting Classic evidence','Questie v10 records preQuestSingle7640; old comments describe separate branches. Guide corrections/new beta need verify before asserting parallel or strict gate.',[q(7641),D]),hard('5',sources=[q(7642),D]),hard('6 AND 9','Completion7643 requires Feed item18775 from step9. Accept7643 after6 unlocks feed9; distinction creates cycle if use completed7 as prerequisite of9.',[q(7643),q(7645),D]),hard('7',sources=[q(7644),D]),row('6 + quest7643 ACTIVE','active-quest prerequisite; NOT earlier completed-step gate','High Classic; unconfirmed Forever','Requires Ancient Equine Spirit7643 IN PROGRESS. Gather biscuits/gold beforehand; feed must complete before step7. Reorder rows or represent acceptance explicitly.',[q(7645),D]),hard('8','No dependency on9 here:9 needed earlier for7.',[q(7646),D]),hard('10','Personal key_scholo NOT required if party can open door.',[q(7647),D])]
M['quelserrar']=[row(note='Book tradeable; looting is one option, purchase bypasses.',sources=[item(18401)]),hard('1','Book7507→7508 handoff→7509 provides blade. Current combined auto questTaken7508 may mark blade obtained too early.',[q(7508),q(7509),D]),hard('2','Need Unfired blade before breath.',[q(7509)]),hard('3','Need heated blade and killed Onyxia; warmth time-limited, old checkbox is history not current possession.',[q(7509)]),hard('4','Treated blade turn-in.',[q(7509)])]
M['att_mc']=[row(note='Min55 Classic; shortcut attunement not prerequisite of raidingMC.',sources=[q(7848)]),soft('1','Conservative: item pre-loot availability not independently verified. No lock until verified.',[q(7848)]),hard('1 AND 2','Accept quest and return fragment.',[q(7848),D])]
M['att_ony_ally']=[row(sources=[q(4182),D])]+[hard(str(i),'Same Alliance character chain; row2 compresses4183→4184→4185→4186→4223→4224.',[D,q(n)]) for i,n in enumerate([4224,4241,4242,4264,4282,4322,6402,6403,6501,6502],1)]
M['att_ony_horde']=[row(sources=[q(4903),D])]+[hard(str(i),'Same Horde character chain.',[D,q(n)]) for i,n in enumerate([4941,4974,6566,6567,6568,6569,6570],1)]+[hard('8','Three first skull quests unlock together, no order among9,10,11.',[D,q(n)]) for n in [6582,6583,6584]]+[hard('9 AND 10 AND 11','All three first skulls needed for Axtroz.',[D,q(6585)]),hard('12',sources=[D,q(6601)]),hard('13',sources=[D,q(6602)])]
M['att_bwl']=[row(note='Min55 quest; orb shortcut optional, UBRS raid entrance alternative.',sources=[q(7761)]),row(note='Can kill Drakkisath without taking command; raid encounter independent; party key_ubrs enough.',sources=[q(7761)]),hard('1 AND 2','Quest active and boss cleared; prior personal kill evidence not necessary if joining cleared instance.',[q(7761),D])]
M['att_naxx']=[row(note='Honored Argent Dawn andlevel60 on character receiving attunement.',sources=[q(9121),D]),hard('1','Honored/Revered/Exalted quest alternatives9121/9122/9123; different costs. External rep_argentdawn whole goal Exalted unnecessary.',[q(9121),D])]
M['key_ubrs']=[row(note='Min57; can collect gems/Unadorned Seal before pickup.',sources=[q(4742),D]),hard('1','4742 collection then4743 forging; condensed guide missing gem collection/handoff detail.',[q(4742),q(4743),D])]
M['key_scholo']=[row(note='Only one row; internal chain unrepresented: faction opening quests→Skeletal Fragments→Mold Rhymes With...→Fire Plume Forged→Araj Scarab→5505/5511. Personal key not required to enter with group/lockpicker.',sources=[q(5505),q(5511),D])]
M['key_brd']=[row(note='Talk to ghost while dead; no earlier row.',sources=[q(3801),D]),hard('1','3802 after3801; requires Ironfel from Fineous then shrine. Personal key not universal dungeon gate.',[q(3802),D])]
M['key_strat']=[row(note='Single boss loot; party key enough for gates.',sources=[item(12382)])]
M['key_dm']=[row(note='Single boss loot; Pusillin conversation/chase within row; no earlier goal prerequisite.',sources=[item(18249)])]
selected=[g for g in cat if g['id'] in M]
lines=['# Quest-chain, weapon, attunement and class-mount dependency audit','', '## What is covered and how should locks work?','', '### Takeaway','Research date: October 8, 2026. Exact current catalogue: 21 goals, 128 numbered flat steps. Classic requirements are a baseline, not confirmation for the incoming Forever beta build.','', '### Cited Findings',f'- Primary implementation baseline: [Questie Classic v10.0.0 database]({D}) and [corrections]({F}). Database key12 preQuestGroup=all prerequisites; key13 preQuestSingle=an allowed predecessor; key25 parentQuest=in progress. Stable version is intentional: master moved database paths.','- Actual local goal text from Data.lua/Library.lua and runtime catalogue after ADDON_LOADED migrations. Quests.lua and Npcs.lua were inspected: they map links/start NPCs, not prerequisite chains. Core migrations move saved ticks (tipsFix,stepsFix231); current step addresses below follow current data, not old save indices.','', '### Inferences','- Hard requirements are minimum direct edges, not every ancestor. AND/OR must be explicit. Local address `n` means that goal flat step n. Cross-goal evidence should work whether or not the other goal is tracked.','- All quest chains, soulbound components and attunements are character-specific. A roster tick from characterA plus materialB or reputationC does not prove any character can complete the action. Use locks as guide ordering only until character provenance exists; completion auto evidence must always override a lock. Never untick finished rows.','- Possession requirements differ from irreversible completion: historical material ticks remain after spending/trading. Keep count rules and quest state as proof rather than assuming saved ticks equal current inventory.','- Gathering and purchases remain available. Group key bypasses and joining cleared instances mean owning a key or personally killing every previous boss is not a universal lock condition.','', '### Gaps','- Forever quest/drop/riding rules not verified after the new beta build. Each Classic edge must retain an unconfirmed Forever status. The existence of an NPC in Forever does not confirm its quest conditions.','', '## What does every current step require?','', '### Takeaway','The following tables enumerate every owned current step including independent materials and provisional edges.','', '### Cited Findings']
for g in selected:
    ident=g['id']; steps=g['steps']; assert len(steps)==len(M[ident]),(ident,len(steps),len(M[ident]))
    lines += ['',f"#### {ident} — {g['name']} ({len(steps)} steps)",'','| Address | Exact current text | Earlier prerequisites | Classification | Confidence | Reason / source |','|---|---|---|---|---|---|']
    for i,(step,r) in enumerate(zip(steps,M[ident]),1):
        text=step if isinstance(step,str) else step['text']; r.update(address=f'{ident}:{i}',text=text)
        esc=lambda s:str(s).replace('|','\\|').replace('\n',' ')
        src='; '.join(f'[source{j}]({u})' for j,u in enumerate(r['sources'],1))
        lines.append('| '+' | '.join(map(esc,[r['address'],text,r['prerequisites'] or 'None',r['classification'],r['confidence'],r['reason']+' '+src]))+' |')
lines += ['', '### Inferences','- Best first-pass fan-out: Lokdelar2 unlocks3/4/5/6; Horde Onyxia8 unlocks9/10/11. Fan-in: Lokdelar7 needs all four heads; Horde Onyxia12 needs all three first skulls. Thunderfury4 demonstrates OR (either binding).','', '### Gaps','- Atiesh8 must be reworded from complete to accept before encoding9. Dreadsteed guide omits actual prerequisites and includes unrelated Inferno; do not ship locks on current list. Charger7/9 need acceptance-versus-completion state or corrected order; strictly earlier-completed-step data alone cannot model it. Charger7641 ordering has conflicting primary dataset versus historical commentary; keep withheld until checked.','', '## Which guide corrections and compatibility traps need a separate pass?','', '### Takeaway','Several guide issues are independent of lock UI and should be corrected with saved-tick remaps if rows move/remove.','', '### Cited Findings',f'- Dreadsteed current4 is unrelated Inferno spell quest. Actual7629 requires7564 AND7625;7630 requires7626/7627/7628;7631 requires7629 AND7630. [Questie]({D}); [Kroshius](https://www.wowhead.com/classic/quest=7603).',f'- Rhokdelar4 names wrong turn-in NPC: Stoma is giver/end for7635. [A Proper String](https://www.wowhead.com/classic/quest=7635).',f'- Charger feed9 has parent7643 active, while7643 completion consumes the feed. [Questie]({D}); [Ancient Equine Spirit](https://www.wowhead.com/classic/quest=7643); [Feed](https://www.wowhead.com/classic/quest=7645).',f'- Thunderfury raw ingredients form Elementium; final turn-in only needs bars,bindings,Essence. Auto quest7786 on defeat11 currently fires at summon turn-in10. [Thunderaan](https://www.wowhead.com/classic/quest=7786).',f'- Atiesh class purification includes Stratholme entity kill and final return; current8 says complete before9 kill. [Purification](https://www.wowhead.com/classic/quest=9257).',f'- Classic Frostsaber quests are repeatable (specialFlags1) and min58 in Questie, contrasting current level40 and daily wording. Verify Forever version before changing. [Questie]({D}).',f'- MC and BWL attunements are entry shortcuts. Personal UBRS/Scholo/DM/BRD keys can be supplied by party/lockpicking as appropriate. [Attunement guide](https://www.wowhead.com/classic/guide/classic-wow-attunements-and-keys-dungeons-raids).','', '### Inferences','- Do not infer locks from row number or automatic-rule coincidence. Thunderfury11 and Atiesh8 demonstrate that existing automatic completion rules/text can represent a different event from the action label.','- Sulfuras hammer purchase bypasses personal recipe/material/profession steps; strict craft-only gating would prevent a valid purchased hammer path.','', '### Gaps','- Exact level/race/riding/quest eligibility in Forever remains a beta-check task. Some drop pre-loot conditions (Core Fragment,Atiesh head/base) are conservative and explicitly withheld/provisional.','']
(p/'quest_dependencies.md').write_text('\n'.join(lines),encoding='utf-8',newline='\n')
(p/'quest_dependency_edges.json').write_text(json.dumps(M,indent=2,ensure_ascii=False),encoding='utf-8',newline='\n')
(p/'quest_owned_ids.json').write_text(json.dumps([g['id'] for g in selected],indent=2),encoding='utf-8',newline='\n')
print('Saved',len(selected),'goals',sum(len(g['steps']) for g in selected),'steps')
